services:
  tailscale-exit:
    image: tailscale/tailscale:latest
    container_name: Tailscale-Exit
    network_mode: service:gluetun
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - TS_AUTHKEY=${TAILSCALE_AUTHKEY}
      - TS_HOSTNAME=nordvpn
      - TS_EXTRA_ARGS=--advertise-exit-node
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_USERSPACE=true
    volumes:
      - ${VOLUMEDIR}/tailscale-exit:/var/lib/tailscale
    depends_on:
      gluetun:
        condition: service_healthy
    restart: always
