# Main docker-compose file for the DockerHost setup

name: ${HOSTNAME}

include:
  - agregarr/docker-compose.yaml
  - dockerproxy-dh/docker-compose.yaml
  - beszel-agent-dh/docker-compose.yaml
  - byparr/docker-compose.yaml
  - cleanuparr/docker-compose.yaml
  - github-runner-dh/docker-compose.yaml
  - gluetun/docker-compose.yaml
#  - grafana/docker-compose.yaml
  - iperf-dh/docker-compose.yaml
  - n8n/docker-compose.yaml
  - nzbget/docker-compose.yaml
  - overseerr/docker-compose.yaml
  - plex/docker-compose.yaml
  - portainer-agent-dh/docker-compose.yaml
#  - prometheus/docker-compose.yaml
  - prowlarr/docker-compose.yaml
  - qbittorrent/docker-compose.yaml
  - radarr/docker-compose.yaml
  - readarr/docker-compose.yaml
  - sonarr/docker-compose.yaml
  - stirling-pdf/docker-compose.yaml
  - tailscale-exit/docker-compose.yaml
  - tautulli/docker-compose.yaml
  - tdarr/docker-compose.yaml
  - tdarr-node/docker-compose.yaml
  - traefik-kop-dh/docker-compose.yaml
  - watchtower-dh/docker-compose.yaml
