services:
  watchtower-dh:
    image: nickfedor/watchtower
    container_name: WatchTower-DH
    network_mode: bridge
    environment:
      # Cron expressions like defined here: https://pkg.go.dev/github.com/robfig/cron#hdr-CRON_Expression_Format
      # Run every day at 6:30 AM
      - WATCHTOWER_SCHEDULE=0 30 6 * * *
      - TZ=Europe/Amsterdam
      - WATCHTOWER_NOTIFICATIONS_HOSTNAME=${HOSTNAME}
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_INCLUDE_STOPPED=true
      - WATCHTOWER_REVIVE_STOPPED=false
      - WATCHTOWER_DEBUG=true
      - WATCHTOWER_NOTIFICATIONS=shoutrrr
      - WATCHTOWER_NOTIFICATION_URL=${WATCHTOWER_NOTIFICATION_URL}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always