---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/settings/

title: AlborWorld HomeLab
startUrl: https://home.alborworld.com

layout:
  - Core Infrastructure:
      style: row
      columns: 3
  - Home & Utilities:
      style: row
      columns: 2
  - Networking & Security:
      style: row
      columns: 2
  - Monitoring & Health:
      style: row
      columns: 2
  - Media Servers:
      style: row
      columns: 3
  - Media Automation:
      style: row
      columns: 3
  - Download Clients:
      style: row
      columns: 2

background: 
  image: https://bing.biturl.top/?resolution=1920&format=image&index=0&mkt=en-US
  blur: lg # sm, xs, md, xl... see https://tailwindcss.com/docs/backdrop-blur
  saturate: 75 # 0, 50, 100... see https://tailwindcss.com/docs/backdrop-saturate
  brightness: 60 # 0, 50, 75... see https://tailwindcss.com/docs/backdrop-brightness
  opacity: 100 # 0-100

cardBlur: md # md, sm, lg
headerStyle: boxed # underlined, boxed, boxedWidgets, clean

theme: dark # or light
color: slate

providers:
  openweathermap: openweathermapapikey
  weatherapi: weatherapiapikey

logpath: /app/
