all:
  children:
    homelab:
      hosts:
        raspberrypi5:
        diskstation:
        dockerhost:

    tailscale_subnet_routers:
      hosts:
        raspberrypi5:
          tailscale_routes: "10.0.4.0/24"

    exit_nodes:
      hosts:
        exit-nordvpn-nl:
          ansible_host: 10.0.4.100  # LAN IP (use Tailscale hostname after provisioning)
          ansible_user: root
          tailscale_hostname: exit-nordvpn-nl
          nordvpn_endpoint: "nl1097.nordvpn.com:51820"
          nordvpn_public_key: "5p4RkybdRU5uaDi90eu4KZPTFif0lKCg4Qp6t1c4F30="
          expected_vpn_country: "NL"
